-- OBSOLET — diese Seed-Daten (Testnamen) werden nicht mehr verwendet.
-- Mitarbeiter werden jetzt automatisch aus auth.users synchronisiert,
-- siehe 20260530_employee_sync.sql. Bewusst NICHT mehr ausführen.
--
-- (Historisch: legte EDL/TMK/MWB/JBR/LHR an.)
